---
tags:
  - java
  - fragment
text: "[[Java]]"
---
# 예외처리 Intro
### 예제 
예외처리 내내 반복할 예제라 정리좀 해놓음
**클래스 설명**
- `NetworkClient` : 외부서버 연결, 데이터 전송, 연결 종료 기능 제공
	-  `connect()` : 외부 서버에 연결한다
	- `send(data)` : 연결한 외부서버에 데이터를 전송한다
	- `disconnect()` : 외부서버와 연결을 해제한다
- `NetworkService` : `NetworkClient`를 사용해서 데이터 전송, 전체적인 흐름 제어
	
- `Main`  : 사용자 입력을 받음

전체적인 흐름 : `Main` 을 통해 사용자의 입력을 받아 `NetworkService`에 전달.
`NetworkService`는 `NetworkClient`를 사용해서 외부서버에 연결 - 데이터 전송 - 연결 종료

`connect()` 가 실패한 경우 `send()` 를 호출하면 안됨
`disconnect()`는 마지막에 무조건 호출해야 함


~~~java
public class NetworkClientV0 {  
  
    private final String address;  
  
    public NetworkClientV0(String address) {  
        this.address = address;  
    }  
  
    public String connect(){  
        // 연결 성공  
        System.out.println(address + "서버 연결 성공");  
        return "success";  
    }  
  
    public String send(String data){  
        //전송 성공  
        System.out.println(address + "서버에 데이터 전송 : " + data);  
        return "success";  
    }  
  
    public void disconnect(){  
        System.out.println(address + "서버 연결 해제");  
    }  
}
~~~

~~~java
public class NetworkServiceV0 {  
  
    public void sendMessage(String data){  
        String address = "http://example.com";  
        NetworkClientV0 client = new NetworkClientV0(address);  
  
        client.connect();  
        client.send(data);  
        client.disconnect();  
  
    }  
}
~~~

~~~java
import java.util.Scanner;

public class MainV0 {
    public static void main(String[] args) {
        NetworkServiceV0 networkService = new NetworkServiceV0();

        Scanner scanner = new Scanner(System.in);

        while(true){
            System.out.print("전송할 문자 : ");
            String input = scanner.nextLine();
            if(input.equals("exit")){
                break;
            }
            networkService.sendMessage(input);
            System.out.println();
        }
        System.out.println("프로그램 정상 종료");
    }
}
~~~
큰 문제 없이 잘 돌아간다 (아직 오류가 없거든)

### 오류상황 발생
외부 서버와 통신할 때는 다양한 문제들이 발생한다.
- 외부서버와 연결에 실패
- 데이터 전송 실패

오류상황을 가상으로 시뮬레이션 해봅시다
- 연결 실패 : error1 - connectError
- 전송 실패 : error2 - sendError

~~~java
public class NetworkClientV1 {  
    private final String address;  
    public boolean connectError;  
    public boolean sendError;  
  
    public NetworkClientV1(String address) {  
        this.address = address;  
    }  
  
    public String connect(){  
        if(connectError){  
            System.out.println(address + " 서버 연결 실패");  
            return "connectError";  
        }  
        // 연결 성공  
        System.out.println(address + "서버 연결 성공");  
        return "success";  
    }  
    public String send(String data){  
        if(sendError){  
            System.out.println(address + " 서버에 데이터 전송 실패 : " + data);  
            return "sendError";  
        }  
  
        //전송 성공  
        System.out.println(address + "서버에 데이터 전송 : " + data);  
        return "success";  
    }  
  
    public void disconnect(){  
        System.out.println(address + "서버 연결 해제");  
    }  
  
    // 오류 이니시에이팅 메서드  
    public void initError(String data){  
        if(data.contains("error1")){  
            connectError = true;  
        }  
        if(data.contains("error2")){  
            sendError = true;  
        }  
    }  
}
~~~

~~~java
public class NetworkServiceV1_1 {  
  
    public void sendMessage(String data){  
        String address = "http://example.com ";  
        NetworkClientV1 client = new NetworkClientV1(address);  
        client.initError(data);  
  
        client.connect();  
        client.send(data);  
        client.disconnect();  
  
    }  
}
~~~

~~~java  
import java.util.Scanner;  
  
public class MainV1 {  
    public static void main(String[] args) {  
        NetworkServiceV1_1 networkService = new NetworkServiceV1_1();  
  
        Scanner scanner = new Scanner(System.in);  
  
        while(true){  
            System.out.print("전송할 문자 : ");  
            String input = scanner.nextLine();  
            if(input.equals("exit")){  
                break;  
            }  
            networkService.sendMessage(input);  
            System.out.println();  
        }  
        System.out.println("프로그램 정상 종료");  
    }  
}
~~~

~~~
전송할 문자 : error2
http://example.com 서버 연결 성공
http://example.com  서버에 데이터 전송 실패 : error2
http://example.com 서버 연결 해제
~~~

자 여기서 문제가 하나 발생하는데
error가 떠도 데이터를 전송해버린다

 - [+] 추가 요구사항
오류가 발생했을 때, 어떤 오류인지 자세한 내역을 남기면 이후 디버깅에 도움이 될것이다.
오류 로그를 남겨야 한다.

### 반환값으로 예외 처리
아까 요구사항과 문제들을 해결해 보자
connectError, sendError 같은 오류코드 반환을 이용해 보자

NetworkServiceV1_1 을 개선했다.
~~~java
public class NetworkServiceV1_2 {  
  
    public void sendMessage(String data){  
        String address = "http://example.com ";  
        NetworkClientV1 client = new NetworkClientV1(address);  
        client.initError(data);  
  
        // client.connect();  
        String connectResult = client.connect();  
        if(!connectResult.equals("success")){ // "success" 가 아니면  
            System.out.println("[네트워크 오류 발생] 오류코드 : " + connectResult);  
            return;  
        }  
  
        // client.send(data);  
        String sendResult = client.send(data);  
        if(!sendResult.equals("success")){ // "success" 가 아니면  
            System.out.println("[네트워크 오류 발생] 오류코드 : " + sendResult);  
            return;  
        }  
  
        client.disconnect();  
  
    }  
}
~~~
- 에러 뜨면 전송안하게 개선
- 에러 로그 남기는거 해결

개선해야 할 부분
~~~java
if(!sendResult.equals("success"))
~~~
if 구문의 조건식이 비직관적이다.


~~~java
private static boolean isError(String connectResult) {  
    return !connectResult.equals("success");  
}
~~~
비효율적이라고 볼 수 도 있겠지만, 따로 메서드로 빼서
isError 라는 이름으로 직관성을 높이는걸 택했다.

~~~java hl:isError
public class NetworkServiceV1_2 {  
  
    public void sendMessage(String data) {  
        String address = "http://example.com ";  
        NetworkClientV1 client = new NetworkClientV1(address);  
        client.initError(data);  
  
        // client.connect();  
        String connectResult = client.connect();  
        if (isError(connectResult)) { // "success" 가 아니면  
            System.out.println("[네트워크 오류 발생] 오류코드 : " + connectResult);  
            return;  
        }  
  
        // client.send(data);  
        String sendResult = client.send(data);  
        if (isError(sendResult)) { // "success" 가 아니면  
            System.out.println("[네트워크 오류 발생] 오류코드 : " + sendResult);  
            return;  
        }  
        client.disconnect();  
    }  
  
    private static boolean isError(String connectResult) {  
        return !connectResult.equals("success");  
    }  
}
~~~

근데 문제가 있음
error가 떠도 disconnect() 가 실행되야함

~~~java
public class NetworkServiceV1_3 {  
  
    public void sendMessage(String data) {  
        String address = "http://example.com ";  
        NetworkClientV1 client = new NetworkClientV1(address);  
        client.initError(data);  
  
        // client.connect();  
        String connectResult = client.connect();  
        if (isError(connectResult)) { // "success" 가 아니면  
            System.out.println("[네트워크 오류 발생] 오류코드 : " + connectResult);  
        }  
        else{  
            String sendResult = client.send(data);  
            if (isError(sendResult)) { // "success" 가 아니면  
                System.out.println("[네트워크 오류 발생] 오류코드 : " + sendResult);  
            }  
        }  
        client.disconnect();  
    }  
  
    private static boolean isError(String connectResult) {  
        return !connectResult.equals("success");  
    }  
}
~~~


##### 문제 의식
- 오류의 종류가 수십개라면 하드코딩이다.
- 정상작동 / 오류처리 과정이 뒤죽박죽 섞여있다. - 심지어 오류처리 과정이 더 많다

**정상흐름과 예외흐름은 분리되어야 한다**

# 예외 처리 이론
예외처리는 프로그램의 안정성, 신뢰성을 높이는데 중요한 역할을 한다.
자바의 예외 처리는 다음 키워드를 사용한다.
`try`, `catch`, `finally`, `throw`, `throws`  + 예외를 다루기 위한 예외처리용 객체


Object - 예외처리의 최상위 부모도 Object이다. (이제 놀랍지도 않음)
예외처리 자체의 최상위 부모는 `Throwable` 이다.

- `Error` : 메모리 부족, 심각한 시스템 오류 - 에플리케이션에서 복구가 불가능한 시스템 예외 (못잡음)
- `Exception` : 체크 예외
	- 실질적인 최상위 예외
- `RuntimeException` : 언체크 예외, 런타임 예외
	- 컴파일러가 체크하지 않는 예외

- [!] 예외는 최대한 구체적으로 잡는게 좋다.
다른 클래스 개념과 마찬가지로, 예외 클래스도 상속이 가능해서 상위 예외를 잡으면 하위 예외도 같이 잡힌다.

### 예외처리의 규칙
예외는 폭탄 돌리기와 같다.
1. 예외는 잡아서 처리하거나, 처리할 수 없으면 던져야한다.
2. 예외를 잡거나 던질 때, 지정한 예외 뿐만 아니라 그 하위 예외도 함께 처리된다.

예외를 처리하지 못하고 계속 던지면 main()에 도달하고, 예외 로그와 함께 시스템이 종료된다.


# 체크 예외 

(런타임을 제외한)`Exception` 과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외이다.
체크 예외는 잡아서 처리하거나, 던지도록 선언해야 한다. 그렇지 않으면 컴파일 오류 발생

~~~java
public class MyCheckedException extends Exception {  
    public MyCheckedException(String message) {  
        super(message);  
    }  
}
~~~

~~~java
public class Client {  
    public void call() throws MyCheckedException{  
  
        //문제 상황  
        throw new MyCheckedException("ex");  
    }  
}
~~~
둘을 잘 구분해야 함
throw : 예외가 터짐
throws : 예외를 던짐

~~~java
public class Service {  
    Client client = new Client();  
    // 잡는 경우  
    public void callCatch() {  
        try {  //예외 감시 로직
            client.call();  
        }catch (MyCheckedException e){  
            // 예외 처리 로직  
            System.out.println("예외 처리, message : " + e.getMessage());  
        }  
        System.out.println("정상 흐름");  
    }  
  
    // 던지는 경우  
    public void catchThrow() throws MyCheckedException {  
        client.call();  
    }  
}
~~~

잡는 메서드와 던지는 메서드를 둘다 만들었다. 이제 Main 을 돌려보자
##### 예외를 catch 한 경우
~~~java
public static void main(String[] args) {  
    Service service = new Service();  
    service.callCatch();  
    System.out.println("정상 종료");  
}
~~~
~~~
예외 처리, message : ex
정상 흐름
정상 종료
~~~
예외를 잡았으니 큰 문제가 발생하지 않았다.
순서

`Client` (예외 발생) -> throw(짬때림) -> `Service` (예외 처리)-> 정상 흐름

##### throws 한 경우
~~~java
public class CheckedThrowMain {  
  
    public static void main(String[] args) throws MyCheckedException{  
        Service service = new Service();  
        service.catchThrow();  
        System.out.println("정상 종료");  
    }  
}
~~~
main() 까지 throws를 던졌기 때문에 컴파일 오류가 발생한다.

# 언체크 예외
`RuntimeException` 과 그 하위 예외는 언체크 예외로 분류된다.
언체크 예외는 말 그대로 컴파일러가 예외를 체크하지 않는다.
체크예외와 거의 비슷하지만, `throws` 를 생략이 가능하다 (자동으로 던진다)

~~~java
public class MyUncheckedException extends RuntimeException {  
    public MyUncheckedException(String message) {  
        super(message);  
    }  
}
~~~

~~~java
public class Client {  
    public void call(){  
        throw new MyUncheckedException("ex");  
    }  
}
~~~

~~~java
public class Service {  
    Client client = new Client();  
  
    public void callCatch(){  
        try {  
            client.call();  
        } catch (MyUncheckedException e) {  
            //예외 처리 로직  
            System.out.println("예외 처리, message : " + e.getMessage());  
        }  
        System.out.println("정상 로직");  
    }  
    // 체크 예외와 다르게 throws 예외 선언을 하지 않아도 됩니다.  
    public void callThrow(){  
        client.call();  
    }  
}
~~~

Throws 할때 명시 생략 빼고는 딱히 큰차이가 없다
메인 돌려봅시다

~~~java
public class UncheckedCarchMain {  
    public static void main(String[] args) {  
        Service service = new Service();  
        service.callCatch();  
        System.out.println("정상 종료");  
    }  
}
~~~
~~~
예외 처리, message : ex
정상 로직
정상 종료
~~~


# 예외 처리 도입

### 예제
맨 처음 예제를 다시 가져와서 만져보자

일단은 예외 생성
~~~java  
public class NetworkClientExceptionV2 extends Exception {  
    private String errorCode;  
  
    public NetworkClientExceptionV2(String errorCode, String message) {  
        super(message);  
        this.errorCode = errorCode;  
    }  
  
    public String getErrorCode() {  
        return errorCode;  
    }  
}
~~~
예외도 객체이기 떄문에 필요한 필드와 메서드를 가질 수 있다.
오류 코드 : 어떤 종류의 오류인지 구분, 예외 안에 오류 코드를 보관한다.
오류 메세지 : 개발자가 보고 이해할 수 있는 설명을 담아둔다.  상위 클래스`Throwable` 의 메서드를 사용한다. 

~~~java
package exception.ex2;  
  
public class NetworkClientV2 {  
    private final String address;  
    public boolean connectError;  
    public boolean sendError;  
  
    public NetworkClientV2(String address) {  
        this.address = address;  
    }  
  
    public void connect() throws NetworkClientExceptionV2{  
        if(connectError){  
            throw new NetworkClientExceptionV2("connectError", address + " 서버 연결 실패");  
        }  
        // 연결 성공  
        System.out.println(address + "서버 연결 성공");  
    }  
    public void send(String data) throws NetworkClientExceptionV2{  
        if(sendError){  
            throw new NetworkClientExceptionV2("sendError",address + " 서버에 데이터 전송 실패 : " + data);  
        }  
        //전송 성공  
        System.out.println(address + "서버에 데이터 전송 : " + data);  
    }  
  
    public void disconnect(){  
        System.out.println(address + "서버 연결 해제");  
    }  
  
    // 오류 이니시에이팅 메서드  
    public void initError(String data){  
        if(data.contains("error1")){  
            connectError = true;  
        }  
        if(data.contains("error2")){  
            sendError = true;  
        }  
    }  
}
~~~
이전 코드와 거의 같다. 예외를 던지는 코드로 수정헀다.
반환값도 필요 없어져서 void로 바꿈

~~~java
public class NetworkServiceV2_1 {  
  
    public void sendMessage(String data) throws NetworkClientExceptionV2 {  
        String address = "http://example.com ";  
        NetworkClientV2 client = new NetworkClientV2(address);  
        client.initError(data);  
  
        client.connect();  
        client.send(data);  
        client.disconnect();  
  
    }  
}
~~~

~~~java
import java.util.Scanner;  
  
public class MainV2 {  
    public static void main(String[] args) throws NetworkClientExceptionV2 {  
        NetworkServiceV2_1 networkService = new NetworkServiceV2_1();  
  
        Scanner scanner = new Scanner(System.in);  
  
        while(true){  
            System.out.print("전송할 문자 : ");  
            String input = scanner.nextLine();  
            if(input.equals("exit")){  
                break;  
            }  
            networkService.sendMessage(input);  
            System.out.println();  
        }  
        System.out.println("프로그램 정상 종료");  
    }  
}
~~~

문제도 롤백됨. 예외를 던지기만 해서 결국에는 오류가 터진다.
disconnect도 작동하지 않음

### 예제 ref
~~~java
public class NetworkServiceV2_2 {  
  
    public void sendMessage(String data) {  
        String address = "http://example.com ";  
        NetworkClientV2 client = new NetworkClientV2(address);  
        client.initError(data);  
  
        try {  
            client.connect();  
        } catch (NetworkClientExceptionV2 e) {  
            System.out.println("[오류] 코드 : " + e.getErrorCode() + ", 메시지 : " + e.getMessage());  
            return;  
        }  
        try {  
            client.send(data);  
        } catch (NetworkClientExceptionV2 e) {  
            System.out.println("[오류] 코드 : " + e.getErrorCode() + ", 메시지 : " + e.getMessage());  
            return;  
        }  
        client.disconnect();  
    }  
}
~~~
try - catch 를 이용하여 예외를 잡았다.
아직 disconnect() 는 작동 안됨
문제시 했던, 정상흐름과 예외흐름이 섞여있음

### 예제 ref2 - 정상-예외 흐름 분리

~~~java
public class NetworkServiceV2_3 {  
  
    public void sendMessage(String data) {  
        String address = "http://example.com ";  
        NetworkClientV2 client = new NetworkClientV2(address);  
        client.initError(data);  
  
        try {  
            client.connect();  
            client.send(data);  
            client.disconnect();  
        } catch (NetworkClientExceptionV2 e) {  
            System.out.println("[오류] 코드 : " + e.getErrorCode() + ", 메시지 : " + e.getMessage());  
  
        }  
    }  
}
~~~
그래 이맛이야

- 하나의 `try` 안에 정상 흐름을 모두 담는다.
- 예외 흐름은  `catch` 블럭안에서 해결한다. 
- main 도 바꿀것이 없다.
- 아직 disconnect() 는 작동 안됨
이제야 가독성과, 코드 흐름이 명확해 졌다.

정상 - 예외 흐름을 보다 잘 분리하려면   throw 도 적절히 이용해서 한곳에서 처리하는것도 중요한듯



마지막 문제는 disconnect() 인데,
try 구문 내부에서 문제가 터지면 catch 흐름으로 빠져버려서 try의 남은 구문은 무시된다.

+

지금 코드의 결함이 하나 있는데, 바로 예측하지 못한 예외는 대비가 되어있지 않다는 것이다.
예측하지 못한 예외가 발생할 떄도 disconnect() 는 작동하지 않는다.

# finally 키워드

자바는 어떤 경우라도 반드시 호출되는 `finally` 기능을 제공한다.

~~~java
try{
}
catch{
}
finally{
}
~~~
- try - catch - finally : 정상 - 예외 - 마무리 흐름
- `finally` 코드블럭은 어떤 경우라도 반드시 호출된다. (심지어 throw 해도 throw 전에 작동)
- 심지어 try - catch 에서 예상하지 못한 예외가 발생해도 `finally` 내부 코드는 반드시 작동한다.


~~~java
public class NetworkServiceV2_5 {  
  
    public void sendMessage(String data) {  
        String address = "http://example.com ";  
        NetworkClientV2 client = new NetworkClientV2(address);  
        client.initError(data);  
  
        try {  
            client.connect();  
            client.send(data);  
  
        } catch (NetworkClientExceptionV2 e) {  
            System.out.println("[오류] 코드 : " + e.getErrorCode() + ", 메시지 : " + e.getMessage());  
  
        }  
        finally {  
            client.disconnect();  
        }  
    }  
}
~~~
굳굳

이제 main 돌려보면 이제 큰 문제는 딱히 없는 듯 하다.

하지만....



# 예외 계층
예외는 하나만 있는것이 아니다.
다양한 예외를 다양화 - 계층화해서 잡으면 더 세밀하게 예외를 처리할 수 있다.
-> 프로그램의 안정성, 신뢰성 향상

계층화는 상속을 통해 가능하다. (예외도 클래스이기 때문)

계층화의 장점
- 상위 예외를 잡으면 하위예외는 다 잡힘
- 하위 에외를 정밀하게 처리도 가능
- exception을 패키지에 모아서 보관 가능


상위 예외
~~~java
public class NetworkClientExceptionV3 extends Exception{  
    public NetworkClientExceptionV3(String message) {  
        super(message);  
    }  
}
~~~

하위 예외

1. 연결 실패 예외
~~~java
public class ConnectExceptionV3 extends NetworkClientExceptionV3{  
    private final String address;  
  
    public ConnectExceptionV3(String address, String message) {  
        super(message);  
        this.address = address;  
    }  
  
    public String getAddress() {  
        return address;  
    }  
}
~~~

2. 전송 실패 예외
~~~java
public class SendExceptionV3 extends NetworkClientExceptionV3{  
    private final String sendData;  
  
    public SendExceptionV3(String sendData, String message) {  
        super(message);  
        this.sendData = sendData;  
    }  
  
    public String getSendData() {  
        return sendData;  
    }  
}
~~~

### 예외 계층화를 적용한 예시

~~~java
package exception.ex3;  
  
import exception.ex3.exception.ConnectExceptionV3;  
import exception.ex3.exception.NetworkClientExceptionV3;  
import exception.ex3.exception.SendExceptionV3;  
  
public class NetworkClientV3 {  
    private final String address;  
    public boolean connectError;  
    public boolean sendError;  
  
    public NetworkClientV3(String address) {  
        this.address = address;  
    }  
  
    public void connect() throws ConnectExceptionV3 {  
        if(connectError){  
            throw new ConnectExceptionV3("connectError", address + " 서버 연결 실패");  
        }  
        // 연결 성공  
        System.out.println(address + "서버 연결 성공");  
    }  
    public void send(String data) throws SendExceptionV3 {  
        if(sendError){  
            throw new SendExceptionV3("sendError",address + " 서버에 데이터 전송 실패 : " + data);  
        }  
        //전송 성공  
        System.out.println(address + "서버에 데이터 전송 : " + data);  
    }  
  
    public void disconnect(){  
        System.out.println(address + "서버 연결 해제");  
    }  
  
    // 오류 이니시에이팅 메서드  
    public void initError(String data){  
        if(data.contains("error1")){  
            connectError = true;  
        }  
        if(data.contains("error2")){  
            sendError = true;  
        }  
    }  
}
~~~

예외의 이름만 봐도 무슨 문제인지 알 수 있게 되었다.

~~~java
public class NetworkServiceV3_1 {  
  
    public void sendMessage(String data) {  
        String address = "http://example.com ";  
        NetworkClientV3 client = new NetworkClientV3(address);  
        client.initError(data);  
  
        try {  
            client.connect();  
            client.send(data);  
  
        }  
        catch (ConnectExceptionV3 e) {  
            System.out.println("[연결 오류] 주소 : " + e.getAddress() + ", 메시지 : " + e.getMessage());  
        }  
        catch (SendExceptionV3 e) {  
            System.out.println("[전송 오류] 전송 데이터 : " + e.getSendData() + ", 메시지 : " + e.getMessage());  
        } 
        finally {  
            client.disconnect();  
        }  
    }  
}
~~~

예외 상황에 따라 필요에 맞는 정보, 메서드를 호출할 수도 있다.
디테일이 증가했다.

~~~java
public class MainV3 {  
    public static void main(String[] args){  
       NetworkServiceV3_1 networkService = new NetworkServiceV3_1();  
        Scanner scanner = new Scanner(System.in);  
  
        while (true) {  
            System.out.print("전송할 문자 : ");  
            String input = scanner.nextLine();  
            if (input.equals("exit")) {  
                break;  
            }  
            networkService.sendMessage(input);  
            System.out.println();  
        }  
        System.out.println("프로그램 정상 종료");  
    }  
}
~~~
굳굳


### 예외 계층 활용
예외가 너무 많을 경우, 하나하나 다 처리하기에는 너무 ~~귀찮다~~ 힘들다
또한 예외도 종류에 따라 중요도, 심각도가 다를것이다.

현재 ConnectExceptionV3 가 가장 중대한 오류라고 가정을 해보자

~~~java
public class NetworkServiceV3_2 {  
  
    public void sendMessage(String data) {  
        String address = "http://example.com ";  
        NetworkClientV3 client = new NetworkClientV3(address);  
        client.initError(data);  
  
        try {  
            client.connect();  
            client.send(data);  
        } catch (ConnectExceptionV3 e) {  
            System.out.println("[연결 오류] 주소 : " + e.getAddress() + ", 메시지 : " + e.getMessage());  
        } catch (NetworkClientExceptionV3 e) {  
            System.out.println("[네트워크 오류] 메시지 : " + e.getMessage());  
        } catch (Exception e) {  
            System.out.println("[알 수 없는 오류] 메시지 : " + e.getMessage());  
        } finally {  
            client.disconnect();  
        }  
    }  
}
~~~
요런식으로 중요도에 따라 catch 순서를 나열
가장 앞에있는 `catch` 를 먼저 잡는다. 
뒤로 갈수록 큰 범위의 예외를 잡도록 세팅


예외 끼리 같은 상속을 받았을 경우에는
~~~java hl:Exception
try {  
    client.connect();  
    client.send(data);  
} catch (ConnectExceptionV3 | Send ExceptionV3 e){

}
~~~
요런식으로 여러 예외를 한번에 잡을 수 도 있다.
메서드 호출, 필드 사용은 제한된다. (슈퍼클래스의 것을 사용하기때문에, 업캐스팅과 비슷한듯)



# 예외처리 best practice

##### 처리할 수 없는 예외
상대 네트워크 서버에 문제가 발생, 데이터 베이스 서버에 문제 발생 같은 예외는 어차피 해결할 수 있는게 거의 없다
오류메시지, 오류페이지를 보여주고, 오류에 최대한 로그를 남겨놓는것이 최선

##### 체크 예외의 thorws 명시가 아주 번거로움
예외의 종류가 수십가지가 넘을때 명시 할려고 하면 아주 골때릴 것이다.

이 두가지 문제를 뭔가 스무스하게 해결할 방법은
처리할 수 없는 예외는 어차피 처리 못하니 로그 남기고, 퉁쳐버리고
체크예외가 아닌 RuntimeException(언체크) 으로 예외를 상속하면 어떨까

~~~java
public class NetworkClientExceptionV4 extends RuntimeException{  
    public NetworkClientExceptionV4(String message) {  
        super(message);  
    }  
}
~~~
요런식으로 최상위 예외를 Runtime 에 상속시키면
하위 예외 클래스들도 자동으로 언체크 예외가 된다.
~~~java
public class NetworkClientV4 {  
    private final String address;  
    public boolean connectError;  
    public boolean sendError;  
  
    public NetworkClientV4(String address) {  
        this.address = address;  
    }  
  
    public void connect() {  
        if (connectError) {  
            throw new ConnectExceptionV4("connectError", address + " 서버 연결 실패");  
        }  
        // 연결 성공  
        System.out.println(address + "서버 연결 성공");  
    }  
  
    public void send(String data) {  
        if (sendError) {  
            throw new SendExceptionV4("sendError", address + " 서버에 데이터 전송 실패 : " + data);  
        }  
        //전송 성공  
        System.out.println(address + "서버에 데이터 전송 : " + data);  
    }  
  
    public void disconnect() {  
        System.out.println(address + "서버 연결 해제");  
    }  
  
    // 오류 이니시에이팅 메서드  
    public void initError(String data) {  
        if (data.contains("error1")) {  
            connectError = true;  
        }  
        if (data.contains("error2")) {  
            sendError = true;  
        }  
    }  
}
~~~
더이상 throws를 명시해주지 않아도 된다.

~~~java
public class NetworkServiceV4 {  
  
    public void sendMessage(String data) {  
        String address = "http://example.com ";  
        NetworkClientV4 client = new NetworkClientV4(address);  
        client.initError(data);  
  
        try {  
            client.connect();  
            client.send(data);  
        } finally {  
            client.disconnect();  
        }  
    }  
}
~~~

catch 안함. 걍 던짐
코드 자체는 굉장히 깔끔해 졌다.

결국에는 main() 에 다 짬때리는 그림인데, main 에서 뭔가를 해줘야 할듯

~~~java
public class MainV4 {  
    public static void main(String[] args){  
       NetworkServiceV4 networkService = new NetworkServiceV4();  
  
        Scanner scanner = new Scanner(System.in);  
  
        while (true) {  
            System.out.print("전송할 문자 : ");  
            String input = scanner.nextLine();  
            if (input.equals("exit")) {  
                break;  
            }  
  
            try {  
                networkService.sendMessage(input);  
            }catch (Exception e){  
                exceptionHandler(e);  
            }  
            networkService.sendMessage(input);  
            System.out.println();  
        }  
        System.out.println("프로그램 정상 종료");  
    }  
    // 공통 예외 처리  
    private static void exceptionHandler(Exception e) {  
        System.out.println("사용자 메시지 : ㅈㅅ");  
        System.out.println("==개발자용 디버깅 메시지==");  
        e.printStackTrace(System.out); // 스택 트레이스 출력  
  
        // 필요하면 에외 별로 별도의 추가 처리 가능  
        if (e instanceof SendExceptionV4 sendEx) {  
            System.out.println("[전송 오류] 전송 데이터 : " + sendEx.getSendData());  
        }  
    }  
}
~~~

`exceptionHandler()` : 예외 처리 메서드를 따로 만들었다.
- 사용자가 디테일한 오류코드 까지 알 필요는 없음
- `printStackTrace()` 기능을 이용하여 개발자에게 디테일한 오류 로그를 남김 (예외를 추적 가능)
- 예외도 객체라는 점을 이용하여 특정 예외에만 작동하도록 `instanceof` 키워드를 사용하여 별도 처리

# try-with-resources

try에서 외부자원을 사용하면 finally에서 외부자원을 반납하는 패턴이 너무 많이 반복되면서,
자바는 `try with resources` 라는 편의 기능을 제공한다.

이 기능을 사용하려면 `AutoCloseable` 인터페이스를 구현해야 한다.

~~~java
public class NetworkClientV5 implements AutoCloseable{}
~~~
인터페이스는 자바 쪽에서 미리 만들어 놨고, implements 로 받아와서 구현만 해주면 된다.

~~~java
@Override  
public void close() throws Exception {  
  
}
~~~

이제 필요에 맞게 오버라이드 해보면
~~~java
@Override  
public void close() {  
    System.out.println("NetworkClientV5.close");  
    disconnect();  
}
~~~
굳굳

오버라이드 한 `close()` 메서드는 try 가 끝나면 자동으로 호출된다.
try 종료 시점에 자동으로 메서드 내용을 수행한다.
(finally) 가 필요없어짐

~~~java hl:NetworkClient
public class NetworkServiceV5 {  
  
    public void sendMessage(String data) {  
        String address = "http://example.com ";  
  
        try(NetworkClientV5 client = new NetworkClientV5(address)) {  
            client.initError(data);  
            client.connect();  
            client.send(data);  
        }  
        catch(Exception e) {  
            System.out.println("[예외 확인] : " + e.getMessage());  
            throw  e;  
        }  
    }  
}
~~~
코드의 의미 압축도가 높아짐...


`try with resources` 장점
- 리소스 누수 방지 : finally 누락 이슈를 방지 할 수 있다.
- 가독성 향상
- 스코프 범위 한정 : 위 예시에서 client 변수의 스코프를 try구문 내부로 한정시킨다. 유지보수가 좋아진다. 